services:
  mongodb:
    image: mongo:7
    container_name: techhub_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: techhub
    networks:
      - techhub_network

  backend:
    build:
      context: ./backend
    container_name: techhub_backend
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      MONGO_URL: mongodb://mongodb:27017/techhub
    depends_on:
      - mongodb
    networks:
      - techhub_network

  frontend:
    build:
      context: ./frontend
    container_name: techhub_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5001
    networks:
      - techhub_network

volumes:
  mongodb_data:

networks:
  techhub_network:
    driver: bridge
